upstream asl-backend {
    server asl-backend:5000;
}

upstream asl-frontend {
    server asl-frontend:80;
}

server {
    listen 80;

    # API endpoint handling
    location /api/ {
        proxy_pass http://asl-backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Frontend handling
    location / {
        proxy_pass http://asl-frontend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}