version: "3"

services:
  asl-backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      - PORT=5000
    ports:
      - "5000:5000"

  asl-frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
