version: "3"

services:
  asl-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=5000
    ports:
      - "5000:5000"

  asl-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - PORT=80
    ports:
      - "80:80"
